(function (global) {
  const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[c]));
  const stateText = (s) => s.attention?.title || ({ idle: '一切就绪，随时开始', listening: '我正在听你说', running: `${s.target.name} 正在处理`, waiting: '有一件事需要你决定', 'missing-config': '先完成两项设置' }[s.stateId]);
  const actions = (s, className = 'action-row') => `<div class="${className}">${s.availableActions.map((a, i) => `<button ${i === 0 ? 'class="primary"' : ''} data-action="${esc(a.id)}">${esc(a.label)}</button>`).join('')}</div>`;
  const channels = (s, mode = '') => `<div class="channel-list ${mode}">${s.channels.map((c) => `<button class="channel ${c.available ? 'ok' : 'off'}" data-action="channel-${c.id}"><span>${c.glyph}</span><b>${c.name}</b><small>${c.detail}</small></button>`).join('')}</div>`;
  const agents = (s) => `<div class="agent-list">${s.agents.map((a) => `<button class="agent agent-${a.state}" data-action="agent-${a.id}"><span class="agent-orb"></span><b>${a.name}</b><small>${a.detail}</small></button>`).join('')}</div>`;
  const repair = (s) => s.configurationIssues.length ? `<div class="repair-strip"><b>需要修复</b>${s.configurationIssues.map((i) => `<button data-action="repair-${i.id}">${i.label}</button>`).join('')}</div>` : '';

  const variants = [
    { id: 'vibe', label: 'Vibe Coding', axis: '从想法到执行的线性编排', strengths: '发起工作路径最清晰', cost: '容易被理解成编程专用工具', fusion: '任务发起器、目标选择、执行前确认', render: (s) => `
      <section class="candidate vibe-view"><header><div><span class="wordmark">OneTone / Flow</span><h1>把一个想法交给电脑</h1></div><div class="context-pill">${s.scene.name} · ${s.target.name}</div></header>
      <div class="flow-board"><div class="flow-step active"><span>1</span><label>你想做什么</label><textarea aria-label="任务描述" placeholder="说一句，或写下你的想法">${s.transcript || ''}</textarea></div><div class="flow-line"></div><div class="flow-step"><span>2</span><label>交给谁</label>${agents(s)}</div><div class="flow-line"></div><div class="flow-step"><span>3</span><label>怎么开始</label>${actions(s, 'stack-actions')}</div></div>
      <footer><strong>${stateText(s)}</strong><span>目标：${s.target.confirmed ? `${s.target.name} / ${s.target.project}` : '需要选择'}</span></footer>${repair(s)}</section>` },
    { id: 'beginner', label: '小白视图', axis: '一句状态和唯一下一步', strengths: '首次使用最容易理解', cost: '高级功能藏得较深', fusion: '人话状态、单一主动作、修复导向', render: (s) => `
      <section class="candidate beginner-view"><header><span class="beginner-logo">一声</span><button data-action="help">我不太懂</button></header><main><div class="friendly-status"><span class="status-face">${s.stateId === 'missing-config' ? '!' : s.stateId === 'waiting' ? '?' : '✓'}</span><p>现在</p><h1>${stateText(s)}</h1><div class="friendly-detail">${s.stateId === 'idle' ? `按住鼠标侧键说话，我会把内容送到 ${s.target.name}` : s.attention?.detail || s.transcript || '不用盯着设置，我会告诉你下一步。'}</div></div>${actions(s, 'single-next')}<button class="why-link" data-action="explain">看看为什么</button></main>${repair(s)}</section>` },
    { id: 'vision', label: 'Vision Pro', axis: '空间焦点与环境层级', strengths: '当前焦点和上下文关系最鲜明', cost: '空间感可能牺牲桌面效率', fusion: '焦点层级、环境降噪、环绕状态', render: (s) => `
      <section class="candidate vision-view"><div class="vision-ambient"></div><header><span class="glass-logo">一声</span><div class="vision-time">桌面空间 · ${s.stateLabel}</div><button data-action="settings">•••</button></header>
      <div class="spatial-stage"><button class="space-orbit orbit-scene" data-action="scene"><small>情境</small><b>${s.scene.name}</b></button><button class="space-orbit orbit-voice" data-action="channel-voice"><small>声音</small><b>${s.channels[0].detail}</b></button><div class="focus-window"><span class="focus-icon">C</span><small>当前焦点</small><h1>${s.target.name}</h1><p>${stateText(s)}</p>${actions(s, 'vision-actions')}</div><button class="space-orbit orbit-agent" data-action="agent-codex"><small>可用帮手</small><b>Codex</b></button><button class="space-orbit orbit-pad" data-action="softpad"><small>控制</small><b>Soft Pad</b></button></div>${repair(s)}</section>` },
    { id: 'quest', label: 'Quest 3', axis: '设备与任务并列的驾驶舱', strengths: '控制中心状态最完整', cost: '信息密度最高', fusion: '设备健康区、模式切换、控制条', render: (s) => `
      <section class="candidate quest-view"><header><div class="quest-brand">ONETONE CONTROL</div><div class="mode-switch"><button class="on" data-action="focus-mode">专注</button><button data-action="global-mode">全局</button></div><div class="quest-clock">${s.stateLabel}</div></header><div class="cockpit"><aside><h2>输入设备</h2>${channels(s, 'vertical')}<button class="utility" data-action="devices">设备管理</button></aside><main><span class="radar-label">当前任务台</span><div class="radar"><div class="radar-ring"></div><div class="radar-core">${s.target.confirmed ? s.target.name.slice(0, 1) : '?'}</div></div><h1>${stateText(s)}</h1><p>${s.target.confirmed ? `${s.target.project} · 输入将发送到 ${s.target.name}` : '尚未建立输入目标'}</p>${actions(s)}</main><aside><h2>Agent 队列</h2>${agents(s)}<div class="telemetry"><span>隐私</span><b>本地处理</b></div></aside></div>${repair(s)}</section>` },
    { id: 'search', label: '搜索引擎', axis: '通过意图召回所有能力', strengths: '无需先理解产品结构', cost: '空输入框的发现性偏弱', fusion: '统一意图入口、分类结果、示例查询', render: (s) => `
      <section class="candidate search-view"><header><span class="search-logo">一声</span><div><button data-action="scene">${s.scene.name}</button><button data-action="settings">设置</button></div></header><main><h1>你想让电脑做什么？</h1><div class="search-box"><span>⌕</span><input aria-label="搜索动作" placeholder="搜索动作、Agent、场景或设置" value="${s.transcript || ''}"><kbd>⌘ K</kbd></div><div class="search-suggestions"><button data-action="speak"><b>开始说话</b><span>把内容发送到 ${s.target.name}</span></button><button data-action="type"><b>向 Codex 发起任务</b><span>输入需求后确认发送</span></button><button data-action="softpad"><b>打开 Soft Pad</b><span>查看你的常用能力</span></button>${s.configurationIssues.map((i) => `<button data-action="repair-${i.id}"><b>${i.label}</b><span>修复后即可使用</span></button>`).join('')}</div><div class="search-foot"><span>${stateText(s)}</span><span>语音、按键、Agent 和设置都可以搜索</span></div></main></section>` },
    { id: 'agents', label: 'Agent 聚合', axis: '多 Agent 的状态与分工协调', strengths: '多 Agent 用户状态最直观', cost: '四通道能力退居次要位置', fusion: '状态带、目标选择器、等待队列', render: (s) => `
      <section class="candidate agents-view"><aside><div class="agents-brand">一声<br><small>Agent Hub</small></div><button class="active" data-action="overview">总览</button><button data-action="new-task">发起工作</button><button data-action="attention">需要我</button><button data-action="connections">连接</button></aside><main><header><div><p>${s.scene.name}</p><h1>你的 Agent 工作台</h1></div><button class="new-agent-task" data-action="type">＋ 发起工作</button></header>${s.attention ? `<div class="attention-banner"><div><b>${s.attention.title}</b><span>${s.attention.detail}</span></div><button data-action="decide">查看并决定</button></div>` : ''}<div class="agent-grid">${s.agents.map((a, i) => `<article class="agent-card ${a.state}"><header><span class="agent-avatar">${a.name[0]}</span><span class="state-dot"></span></header><h2>${a.name}</h2><p>${a.detail}</p><div>${i === 0 ? `目标 · ${s.target.project || '未确认'}` : '准备接收新任务'}</div><button data-action="agent-${a.id}">${a.state === 'waiting' ? '去处理' : '选择'}</button></article>`).join('')}</div><section class="agent-launch"><div><small>统一发起</small><b>${stateText(s)}</b></div>${actions(s)}</section></main></section>` },
    { id: 'notion', label: 'Notion', axis: '可组织的模块化工作空间', strengths: '内容清楚且便于长期扩展', cost: '容易变成卡片墙', fusion: '可折叠分区、渐进展示、个性首页', render: (s) => `
      <section class="candidate notion-view"><aside><div class="notion-workspace"><span>N</span><b>一声工作区</b></div><nav><button class="active" data-action="home">⌂ 首页</button><button data-action="scenes">◫ 我的场景</button><button data-action="agents">◉ Agents</button><button data-action="settings">⚙ 设置</button></nav><div class="notion-side-note">当前目标<br><b>${s.target.name}</b></div></aside><main><header><span class="page-icon">🎛</span><h1>桌面控制中心</h1><p>${s.scene.name} · ${stateText(s)}</p></header><section class="notion-callout"><b>${s.stateId === 'idle' ? '从这里开始' : s.stateLabel}</b><span>${s.attention?.detail || '选择一种方式，发起你接下来要做的事。'}</span>${actions(s)}</section><div class="notion-columns"><section><h2>常用动作</h2><div class="notion-list"><button data-action="speak">🎙 按住说话 <span>发送到 ${s.target.name}</span></button><button data-action="softpad">▦ 打开 Soft Pad <span>6 个常用动作</span></button><button data-action="scene">◈ 切换场景 <span>${s.scene.name}</span></button></div></section><section><h2>输入方式</h2>${channels(s, 'notion-channels')}</section></div>${repair(s)}</main></section>` },
    { id: 'raycast', label: 'Raycast', axis: '键盘优先的即时命令', strengths: '高频操作速度最快', cost: '新用户发现性最弱', fusion: '命令面板、快捷动作、键盘导航', render: (s) => `
      <section class="candidate raycast-view"><div class="ray-window"><header><div class="ray-search"><span>⌕</span><input aria-label="命令搜索" placeholder="搜索 OneTone 命令…" value="${s.transcript || ''}"><kbd>⌘ K</kbd></div></header><div class="ray-body"><main><p class="ray-section">建议</p><button class="ray-command selected" data-action="${s.availableActions[0].id}"><span class="ray-icon">◉</span><span><b>${s.availableActions[0].label}</b><small>${stateText(s)}</small></span><kbd>↵</kbd></button>${s.availableActions.slice(1).map((a) => `<button class="ray-command" data-action="${a.id}"><span class="ray-icon">${a.id.includes('repair') ? '⚙' : '◇'}</span><span><b>${a.label}</b><small>${s.target.name}</small></span></button>`).join('')}<p class="ray-section">控制中心</p><button class="ray-command" data-action="softpad"><span class="ray-icon">▦</span><span><b>打开 Soft Pad</b><small>查看全部能力</small></span><kbd>⌘ P</kbd></button><button class="ray-command" data-action="scene"><span class="ray-icon">◫</span><span><b>切换场景</b><small>${s.scene.name}</small></span></button></main><aside><span class="ray-preview-icon">一</span><h2>${s.target.name}</h2><p>${stateText(s)}</p>${channels(s, 'ray-channels')}</aside></div><footer><span>${s.stateLabel}</span><div><kbd>↑↓</kbd> 选择 <kbd>↵</kbd> 执行</div></footer></div></section>` },
  ];
  global.HomePrototypeVariants = variants;
})(window);
