(function(global){
  'use strict';

  function ed(){ return global.OneToneMappingEditorState; }
  var M=global.OneToneMappingEditActions;
  function tx(){ return global.OneToneAppTextUtils; }
  function vs(){ return global.OneToneVoiceUiState; }
  function conflict(){ return global.OneToneMappingConflictState; }

  function register(deps){
    global.__vp_mapping_meta_render_hooks__={
      normalizeTriggerKey:deps.normalizeTriggerKey,
      friendlyKeyName:deps.friendlyKeyName,
      ensureMappingExtras:deps.ensureMappingExtras
    };
    global.__vp_mapping_recording_hooks__={
      getEditorTriggerKey:ed().getEditorTriggerKey,
      setEditorTriggerKey:ed().setEditorTriggerKey,
      getEditorTargetKey:ed().getEditorTargetKey,
      setEditorTargetKey:ed().setEditorTargetKey,
      ensureConfig:deps.ensureConfig,
      resetTargetCapture:deps.resetTargetCapture,
      renderSchemeSwitch:deps.renderSchemeSwitch,
      renderMappingList:deps.renderMappingList,
      abandonDraftIfPristine:deps.abandonDraftIfPristine,
      render:deps.render,
      friendlyKeyName:deps.friendlyKeyName,
      isAutoTriggerMapping:deps.isAutoTriggerMapping,
      buildPeripheralTriggerSource:deps.buildPeripheralTriggerSource,
      pushLog:deps.pushLog,
      save:deps.save,
      ensureMappingExtras:deps.ensureMappingExtras,
      getAppLang:deps.getAppLang,
      toast:deps.toast,
      ui:deps.ui,
      schemeStepFocus:deps.schemeStepFocus,
      syncKeySchemeTimeline:deps.syncKeySchemeTimeline,
      uiBootstrapping:deps.uiBootstrapping,
      updatePrimaryCTA:deps.updatePrimaryCTA,
      renderHeroBadges:deps.renderHeroBadges,
      renderHome:deps.renderHome,
      renderMicDevices:deps.renderMicDevices,
      renderAddButton:deps.renderAddButton,
      armTriggerLeftClickIgnore:deps.armTriggerLeftClickIgnore,
      armTargetLeftClickIgnore:deps.armTargetLeftClickIgnore,
      normalizeTriggerKey:deps.normalizeTriggerKey,
      isAllowedTriggerKey:deps.isAllowedTriggerKey,
      sanitizeTargetCombo:deps.sanitizeTargetCombo,
      normalizeMediaTargetKey:deps.normalizeMediaTargetKey,
      maybeEnableMappingAfterComplete:deps.maybeEnableMappingAfterComplete,
      shouldIgnoreTriggerLeftClickCapture:deps.shouldIgnoreTriggerLeftClickCapture,
      armTriggerPeripheralGuard:ed().armTriggerPeripheralGuard,
      getPendingNewDraftId:ed().getPendingNewDraftId,
      setPendingNewDraftId:ed().setPendingNewDraftId
    };
    global.__vp_mapping_recording_input_hooks__={
      normalizeMediaTargetKey:deps.normalizeMediaTargetKey,
      buildPeripheralTriggerSource:deps.buildPeripheralTriggerSource,
      friendlyKeyName:deps.friendlyKeyName,
      pushLog:deps.pushLog,
      playSoundCue:deps.playSoundCue,
      toast:deps.toast,
      save:deps.save,
      render:deps.render,
      shouldIgnoreTriggerLeftClickCapture:deps.shouldIgnoreTriggerLeftClickCapture,
      shouldIgnoreTargetLeftClickCapture:deps.shouldIgnoreTargetLeftClickCapture,
      triggerPeripheralGuardUntil:ed().triggerPeripheralGuardUntil,
      armTriggerPeripheralGuard:ed().armTriggerPeripheralGuard
    };
    global.__vp_mapping_trash_menu_hooks__={
      t:deps.t,
      ensureConfig:deps.ensureConfig,
      sortedMappings:deps.sortedMappings,
      isDraftMapping:deps.isDraftMapping,
      editorTargetForMapping:deps.editorTargetForMapping,
      removeDraftMapping:deps.removeDraftMapping,
      newMappingId:deps.newMappingId,
      syncEditorFromSelection:deps.syncEditorFromSelection,
      save:deps.save,
      saveAsync:deps.saveAsync,
      render:deps.render,
      toast:deps.toast,
      friendlyPair:deps.friendlyPair
    };
    global.__vp_scheme_switch_feedback_hooks__={
      t:deps.t,
      syncEditorFromSelection:deps.syncEditorFromSelection,
      renderMappingList:deps.renderMappingList,
      renderEditor:deps.renderEditor,
      render:deps.render,
      toast:deps.toast
    };
    global.__vp_mapping_test_send_hooks__={
      t:deps.t,
      ensureConfig:deps.ensureConfig,
      flushAllEditorToMappings:deps.flushAllEditorToMappings,
      mappingById:deps.mappingById,
      selectedMapping:deps.selectedMapping,
      sortedMappings:deps.sortedMappings,
      editorTargetForMapping:deps.editorTargetForMapping,
      editorTriggerForMapping:deps.editorTriggerForMapping,
      friendlyPair:deps.friendlyPair,
      friendlyKeyName:deps.friendlyKeyName,
      conflictsForMapping:deps.conflictsForMapping,
      otherIdInConflict:deps.otherIdInConflict,
      mappingTargetKey:deps.mappingTargetKey,
      playSoundCue:deps.playSoundCue,
      renderMappingList:deps.renderMappingList,
      renderHomeLiveKeyPanel:deps.renderHomeLiveKeyPanel
    };
    global.__vp_mapping_list_hooks__={
      escHtml:tx().escHtml,
      friendlyKeyName:deps.friendlyKeyName,
      friendlyPair:deps.friendlyPair,
      ensureConfig:deps.ensureConfig,
      ensureMappingTiming:deps.ensureMappingTiming,
      ensureMappingExtras:deps.ensureMappingExtras,
      isAutoTriggerMapping:deps.isAutoTriggerMapping,
      formatTimingSec:deps.formatTimingSec,
      keyFinishPreviewText:deps.keyFinishPreviewText,
      voiceUiSnapshot:vs().snapshot,
      sessionActiveState:tx().sessionActiveState,
      openMenuId:deps.openMenuId,
      testSendState:deps.testSendState,
      testSendMappingId:deps.testSendMappingId,
      recordingMode:deps.recordingMode,
      recordingMappingId:deps.recordingMappingId,
      syncAllTimingRanges:deps.syncAllTimingRanges,
      selectedDisplayTriggerKey:deps.selectedDisplayTriggerKey,
      selectedDisplayTargetKey:deps.selectedDisplayTargetKey,
      updatePrimaryCTA:deps.updatePrimaryCTA,
      applyKeyWakeRecordingUi:deps.applyKeyWakeRecordingUi,
      renderKeySchemeCardHeader:deps.renderKeySchemeCardHeader,
      syncKeySchemeTimeline:deps.syncKeySchemeTimeline,
      schemeStepFocus:deps.schemeStepFocus,
      renderHome:deps.renderHome,
      renderRecordCancelBar:deps.renderRecordCancelBar,
      save:deps.save,
      render:deps.render
    };
    global.__vp_mapping_list_ui_hooks__={
      t:deps.t,
      liveUpdateTimingRange:deps.liveUpdateTimingRange,
      ensureMappingTiming:deps.ensureMappingTiming,
      isSavedMapping:deps.isSavedMapping,
      save:deps.save,
      renderKeyFinishFlowPanel:deps.renderKeyFinishFlowPanel,
      renderMappingList:deps.renderMappingList,
      renderHomeKeyFinishPreview:deps.renderHomeKeyFinishPreview,
      focusMapping:deps.focusMapping,
      openSettings:deps.openSettings,
      cancelRecording:deps.cancelRecording,
      startNativeRestoreRecord:deps.startNativeRestoreRecord,
      startMappingSwitchRecord:deps.startMappingSwitchRecord,
      removeMappingSwitchKey:M.removeMappingSwitchKey,
      setMappingEnabled:M.setMappingEnabled,
      fireTestSend:deps.fireTestSend,
      syncEditorFromSelection:deps.syncEditorFromSelection,
      closeFloatMenu:deps.closeFloatMenu,
      render:deps.render,
      isCurrentDraftComplete:deps.isCurrentDraftComplete,
      toast:deps.toast,
      renderDraftHint:deps.renderDraftHint,
      ensureConfig:deps.ensureConfig,
      newMappingId:deps.newMappingId,
      setPendingNewDraftId:ed().setPendingNewDraftId,
      setEditorTriggerKey:ed().setEditorTriggerKey,
      setEditorTargetKey:ed().setEditorTargetKey,
      renderRecordCancelBar:deps.renderRecordCancelBar,
      duplicateMapping:deps.duplicateMapping,
      deleteMappingFromMenu:deps.deleteMappingFromMenu,
      reorderMapping:deps.reorderMapping,
      openFloatMenu:deps.openFloatMenu,
      openMenuId:deps.openMenuId,
      menuAnchorBtn:deps.menuAnchorBtn
    };
    global.__vp_key_finish_flow_ui_hooks__={
      handleKeyFinishFlowInput:deps.handleKeyFinishFlowInput,
      handleKeyFinishFlowClick:deps.handleKeyFinishFlowClick,
      focusSchemeEditStep:deps.focusSchemeEditStep,
      selectedMapping:deps.selectedMapping,
      isSavedMapping:deps.isSavedMapping,
      setMappingEnabled:M.setMappingEnabled
    };
    global.__vp_mapping_core_hooks__={
      escHtml:tx().escHtml,
      friendlyKeyName:deps.friendlyKeyName,
      homeMappingPairLine:deps.homeMappingPairLine,
      ensureConfig:deps.ensureConfig,
      save:deps.save,
      render:deps.render,
      toast:deps.toast,
      onboardIsOpen:deps.onboardIsOpen,
      normalizeTriggerKey:deps.normalizeTriggerKey,
      renderMappingList:deps.renderMappingList,
      renderSchemeSwitch:deps.renderSchemeSwitch,
      renderTestSendButton:deps.renderTestSendButton,
      renderAddButton:deps.renderAddButton,
      renderDraftHint:deps.renderDraftHint,
      conflictRows:conflict().rows,
      expandedAdvIds:ed().expandedAdvIds,
      getPendingNewDraftId:ed().getPendingNewDraftId,
      setPendingNewDraftId:ed().setPendingNewDraftId,
      getRecordingMappingId:deps.getRecordingMappingId,
      setRecordingMappingId:deps.setRecordingMappingId,
      getEditorTriggerKey:ed().getEditorTriggerKey,
      setEditorTriggerKey:ed().setEditorTriggerKey,
      getEditorTargetKey:ed().getEditorTargetKey,
      setEditorTargetKey:ed().setEditorTargetKey,
      syncEditorFromSelection:deps.syncEditorFromSelection,
      flushAllEditorToMappings:deps.flushAllEditorToMappings
    };
    global.__vp_key_finish_flow_render_hooks__={
      ensureConfig:deps.ensureConfig,
      save:deps.save,
      selectedMapping:deps.selectedMapping,
      isSavedMapping:deps.isSavedMapping,
      isDraftMapping:deps.isDraftMapping,
      selectedDisplayTriggerKey:deps.selectedDisplayTriggerKey,
      selectedDisplayTargetKey:deps.selectedDisplayTargetKey,
      friendlyKeyName:deps.friendlyKeyName,
      homeSchemeLabel:deps.homeSchemeLabel,
      schemeMappingHasConflict:deps.schemeMappingHasConflict,
      isCurrentDraftComplete:deps.isCurrentDraftComplete,
      ensureMappingTiming:deps.ensureMappingTiming,
      keyFinishPreviewText:deps.keyFinishPreviewText,
      renderHomeKeyFinishPreview:deps.renderHomeKeyFinishPreview,
      renderMappingList:deps.renderMappingList,
      voiceUiSnapshot:vs().snapshot,
      escHtml:tx().escHtml
    };
  }

  global.OneToneMappingHooks={register:register};
})((typeof window!=='undefined')?window:globalThis);
